---

#
#
#

stages:
  - build

build-chart:
  stage: build
  image:
    name: registry.REDACTED.net/helm
    entrypoint: [""]
  script:
    - helm repo add REDACTED https://charts.REDACTED.net
    - helm repo update
    - helm dependency update ./${CI_PROJECT_NAME}
    - helm package --version=${CI_COMMIT_REF_NAME} ./${CI_PROJECT_NAME}
    - helm lint --strict ${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}.tgz
    - curl --silent --data-binary "@${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}.tgz" --write-out "\n" https://charts.REDACTED.net/api/charts
  tags:
    - docker
    - builder
    - uk
