---

#
#
#

prometheus_config:
  global:
    scrape_interval: 60s
    evaluation_interval: 60s
    external_labels:
        monitor: 'codelab-monitor'
  rule_files:
    # - "rule1.rules"
    # - "rule2.rules"
  scrape_configs:
    - job_name: 'prometheus'
      # metrics_path defaults to '/metrics'
      # scheme defaults to 'http'.
      static_configs:
        - targets:
          - 'localhost:9090'
          labels:
            group: 'production'
    - job_name: '{{ ansible_hostname }}'
      scrape_interval: 15s
      static_configs:
        - targets:
          - 'localhost:9100'
prometheus_install_dir: '/opt'
prometheus_config_file: "{{ prometheus_install_dir }}/prometheus/prometheus.yml"
prometheus_download_url: 'https://github.com/prometheus/prometheus/releases/download'
prometheus_download: '{{ prometheus_download_url }}/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz'
prometheus_local_storage: '/var/lib/prometheus/data'
prometheus_source_dir: '/usr/local/src'
prometheus_user_info:
  group: 'prometheus'
  user: 'prometheus'
prometheus_version: '1.6.1'
