---

#
#
#

apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Chart.Name }}
  {{- if .Values.service.externalIPs }}
  externalIPs:
  {{- range .Values.service.externalIPs }}
    - {{ . }}
  {{- end }}
  {{- end }}
  ports:
  - name: web
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
